name: hikayaats
description: Ada cerita dibalik peristiwa

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter_bloc: ^8.0.0
  flutter_svg: ^0.23.0+1
  flutter_staggered_grid_view: ^0.4.0
  flip_card: ^0.6.0
  get: ^4.3.8
  google_sign_in: ^5.0.5
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true

flutter_icons:
  image_path: "assets/icons/chat.svg"
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700